# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# This config affects Python files in the current directory
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-merge-conflict
    - id: no-commit-to-branch
      args: [--branch, master]
    - id: check-ast
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: license_files/.*\.license$
    - id: check-added-large-files
      args: ['--maxkb=750']
      exclude: poetry\.lock$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
        exclude: license_files/.*\.license$
